### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by kieferro** [prettierlichess/prettierlichess#108]
- [ ] Fix reported bugs
- [ ] Add option to turn the extension on and off
- [ ] Move highlights settings (#113)
- [x] Debug output
- [x] gitattributes
- [x] Fix text on `practice`-site (Doesn't use `textColor` attribute)
- [x] Make trainer and streamer page dependent on colour variables
- [x] Add different color for own game in lobby
- [x] Update `package.json` to not include the repo from pabuisson
- [x] Check for lichess in URL before reloading for `Reset to default` or `Import`
- [x] Color of settings on hover
- [x] Time settings on profile rating graph
- [x] Play/New Game - Colors
- [x] Streamer + Coaches - Horizontal lines on bright layout
